### PR TITLE
Locale for it, de, es, fr

### PR DESCRIPTION
**Pull request by pyMan**
Added locale for it, de, es, fr.
Google translate was used for de, es, fr.

Bugfix: when create a new filter from another filter, the new filter was not "for_everyone" if so set.

### CODE REVIEW

**Comment by pyMan** [comment]
@thomst I'd need a 0.3 release with these locales, if ok.

But in that release I'd also need global filter being editable by its owner. See https://github.com/thomst/django-admin-filter/pull/6#issuecomment-766858329

**Comment by thomst** [comment]
> Bugfix: when create a new filter from another filter, the new filter was not "for_everyone" if so set.

I've already fixed that.

**Comment by thomst** [comment]
> @thomst I'd need a 0.3 release with these locales, if ok.
> 
> But in that release I'd also need global filter being editable by its owner. See [#6 (comment)](https://github.com/thomst/django-admin-filter/pull/6#issuecomment-766858329)

@pyMan I will do a release soon. Please checkout the current master and try out the editing global filters by giving your user the extra permisssion. See my comment in [#6](https://github.com/thomst/django-admin-filter/pull/6#issuecomment-767375527).

**Comment by thomst** [comment]
> Bugfix: when create a new filter from another filter, the new filter was not "for_everyone" if so set.

@pyMan Please do not mess up pull request. It is more easy to handle if you strictly do one pullrequest for each seperate issue.

**Comment by pyMan** [comment]
Hi @thomst, I have seen 0.3 and 0.4 releases, but I was wondering why locales are not still included with pip install.

**Comment by thomst** [comment]
> Hi @thomst, I have seen 0.3 and 0.4 releases, but I was wondering why locales are not still included with pip install.

@pyMan sorry... that was me... Again forgot to update the MANIFEST file. Locales should be included in version 0.5.

**Pull request merged**
