### PR TITLE
Manage global and personal filters

### PR DESCRIPTION
**Pull request by pyMan**
Users can create personal filters (only the owner che see it) or global filters (any user can see it, but only the owner can delete it).

### CODE REVIEW

**Comment by pyMan** [comment]
@thomst thanks for merging.

Anyway I think global filters should still be editable by its owner, like personal filters.

**Comment by thomst** [comment]
> Anyway I think global filters should still be editable by its owner, like personal filters.

@pyMan Since everyone could mess up the admin-page of each other user by creating stupid global filters, I decided to implement an extra permission for handling global filters. They can now commonly created, edited and deleted by all those users having that permission.

**Comment by thomst** [comment]
As soon as I find the time to update the README and add some tests for handling global filters I will create a new release.
@pyMan Thanks for your support.

**Comment by pyMan** [comment]
> 
> 
> > Anyway I think global filters should still be editable by its owner, like personal filters.
> 
> @pyMan Since everyone could mess up the admin-page of each other user by creating stupid global filters, I decided to implement an extra permission for handling global filters. They can now commonly created, edited and deleted by all those users having that permission.

Cool and it works! Thank you

**Pull request merged**
